### ISSUE TITLE
SECRET Token structure

### ISSUE THREAD

**Issue by gregory1506** [giswqs/geemap-streamlit#1]
Is the secret token a json file? Or is it similar to what comes back from ee.Authenticate() with the webpage redirect?

**Comment by giswqs** [comment]
You can find the token in the following file path:

```
Windows: C:\Users\USERNAME\.config\earthengine\credentials
Linux: /home/USERNAME/.config/earthengine/credentials
MacOS: /Users/USERNAME/.config/earthengine/credentials
```

Open the file and copy the token 
![](https://i.imgur.com/wDQ5WiS.png)

Go to https://share.streamlit.io and set it as a secret for your app.
![](https://i.imgur.com/enB1Ljj.png)

**Comment by gregory1506** [comment]
i dont seem to have any of those folders.

Edit:. Found It...Thanks
